# Makefile template for shared library
 
INCPATH = -I/usr/packages/boost_1_57_0 -I/usr/packages/cpp-netlib-0.11.1-final -I/usr/packages/rapidxml_1_0_0 -I/usr/packages/ohNet-Linux-x86-Release/include/ohnet

CC = g++-4.9
CXX = g++-4.9
CFLAGS = -std=c++0x -fPIC -Wall -Wextra -O2 -c -pthread -I /usr/development/raumfeld/RaumKernel
CXXFLAGS = -std=c++0x -fPIC -Wall -Wextra -O2 -c -pthread -I /usr/development/raumfeld/RaumKernel
LDFLAGS = -lm -static-libgcc -static-libstdc++ -pthread -lrt -Wl,-rpath,lib/

LIBSDEF = libs/raumkern.so /usr/packages/libs/libohNetCore.a /usr/packages/libs/libohNetDevices.a /usr/packages/libs/libohNetProxies.a /usr/packages/libs/libcppnetlib-uri.a /usr/packages/libs/libboost_system.a /usr/packages/libs/libboost_thread.a /usr/packages/libs/libboost_signals.a /usr/packages/libs/libboost_date_time.a /usr/packages/libs/libboost_regex.a 

RM = rm -f 
TARGET_EXEC = raumServer
 
SRCS = RaumServer.cpp RaumServerGUI.cpp
OBJS = $(SRCS:.cpp=.o)


.PHONY: all
all: ${TARGET_EXEC}
 
$(TARGET_EXEC): $(OBJS)
	$(CC) ${LDFLAGS} -o $@ $^ $(LIBSDEF)
 
$(SRCS:.cpp=.d):%.d:%.cpp
	$(CC) $(CFLAGS) -MM $< >$@
 
include $(SRCS:.cpp=.d)
 

.PHONY: clean
clean:
	-${RM} ${TARGET_EXEC} ${OBJS} $(SRCS:.cpp=.d) 